[package]
name = "age-plugin-yubikey"
description = "[BETA] YubiKey plugin for age."
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
repository = "https://github.com/str4d/age-plugin-yubikey"
readme = "README.md"
keywords = ["age", "cli", "encryption", "yubikey"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
age-core = "0.5"
age-plugin = "0.0"
bech32 = "0.7.2"
console = "0.14"
der-parser = "4.1"
elliptic-curve = "0.6"
gumdrop = "0.8"
p256 = "0.5"
sha2 = "0.9"
x509-parser = "0.8"
yubikey-piv = { version = "0.1", features = ["untested"] }

[patch.crates-io]
age-core = { git = "https://github.com/str4d/rage.git", rev = "d8fd951e059d9f7116b2b9dd0d176798a11b49f3" }
age-plugin = { git = "https://github.com/str4d/rage.git", rev = "d8fd951e059d9f7116b2b9dd0d176798a11b49f3" }
